version: '3'
services:
  aiengine:
    container_name: aiengine
    restart: unless-stopped
    build:
      context: aiengine
      dockerfile: Dockerfile
    image: jasai/aiengine
    ports:
      - "9221:5000"
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    command:
      - --encryptionEnv #optional
      - ENCRYPTION #optional
    environment:
      ENCRYPTION: studentAI2023 #optional
    ports:
      - "9220:8090"
    volumes:
      - ./auth/pb_data:/pb_data
      - ./auth/pb_migrations:/pb_migrations
      - ./auth/pb_public:/pb_public
    healthcheck: #optional (recommended) since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

