version: '3'
services:
  app:
    container_name: jasapp
    restart: unless-stopped
    build:
      context: app
      dockerfile: Dockerfile
    image: jasai/jasapp:latest
    ports:
      - "9221:5000"
  ai:
    container_name: jasai
    restart: unless-stopped
    image: embedchain/rest-api:latest 
    ports:
      - "9222:8080"
  auth:
    container_name: jasauth
    restart: unless-stopped
    build:
      context: auth
      dockerfile: Dockerfile
    image: jasai/jasauth:latest 
    ports:
      - "9220:8090"
    volumes:
      - pocketbase-volume:/app/data

volumes:
  pocketbase-volume:
    name: pocketbase-volume


